### PR TITLE
Remove unused NPM variables

### PR DESCRIPTION
**Pull request by medwards1771**
NOTE: I will also be removing these values from the AWS bucket:
s3://buildkite-secrets-policygenius/eslint-config-policygenius/env

These values are not read anywhere in the eslint-config-policygenius repo and are no
longer needed.

### CODE REVIEW

**Review by jmcolella — APPROVED** [review]
@medwards1771 LGTM

**Comment by medwards1771** [comment]
@jmcolella are you able to merge this PR? I am not authorized to do so.

**Comment by jmcolella** [comment]
@medwards1771 Neither am I 🤔 . Can someone on Platform authorize the team to have merge permissions?

**Comment by mttrms** [comment]
I also am unable to merge

**Review by mttrms — APPROVED** [review]
thanks for removing these - I think John and I meant to do that while we were building the pipeline but didn't get around to it before merging

**Comment by medwards1771** [comment]
How strange! @jmcolella I will ask if anyone on Platform has admin access to this repo and can update the merge settings

**Comment by medwards1771** [comment]
@mttrms @jmcolella Ok, got access to change the settings on this repo. I updated the branch protection rules to no longer restrict merging to randy-the-robot (:side-eye:) and added you both as Admins since you are the primary and secondary steward.

**Pull request merged**
